/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programadeestoque;
import javax.swing.JOptionPane;
/**
 *
 * @author matheus.moliveira36
 */
public class cadastrodeclientes extends javax.swing.JFrame {

    /**
     * Creates new form cadastrodeclientes
     */
    public cadastrodeclientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reservas = new javax.swing.JButton();
        Recepcao = new javax.swing.JButton();
        estoque = new javax.swing.JButton();
        despesas = new javax.swing.JButton();
        relatorios = new javax.swing.JButton();
        faturamento = new javax.swing.JButton();
        encerrar = new javax.swing.JButton();
        valortotal = new javax.swing.JTextField();
        salvarcliente = new javax.swing.JButton();
        nomehospede1 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/quartos.png"))); // NOI18N
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });
        jPanel1.add(reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        Recepcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/recep.png"))); // NOI18N
        Recepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecepcaoActionPerformed(evt);
            }
        });
        jPanel1.add(Recepcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, 60));

        estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/estoque.png"))); // NOI18N
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });
        jPanel1.add(estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        despesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/despesa.png"))); // NOI18N
        despesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despesasActionPerformed(evt);
            }
        });
        jPanel1.add(despesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/relatorio.png"))); // NOI18N
        relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, -1, -1));

        faturamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/faturamento.png"))); // NOI18N
        faturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturamentoActionPerformed(evt);
            }
        });
        jPanel1.add(faturamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 750, -1, -1));

        encerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/desligar.png"))); // NOI18N
        encerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarActionPerformed(evt);
            }
        });
        jPanel1.add(encerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 930, -1, -1));

        valortotal.setText("R$");
        jPanel1.add(valortotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 320, 240, 60));

        salvarcliente.setText("SALVAR");
        salvarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarclienteActionPerformed(evt);
            }
        });
        jPanel1.add(salvarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 980, 90, 40));
        jPanel1.add(nomehospede1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 240, 60));

        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1716918695650L), null, java.util.Calendar.DAY_OF_MONTH));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 320, 150, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quarto Deluxe", "Suite Junior", "Suite Executiva", "Suite Presidencial", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 230, 60));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 540, 240, 70));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 540, 240, 70));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 730, 240, 70));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 730, 240, 70));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 730, 240, 70));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 240, 70));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 240, 70));

        jSpinner2.setModel(new javax.swing.SpinnerListModel(new String[] {"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"}));
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 90, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/controle de acesso cenario.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecepcaoActionPerformed
        // TODO add your handling code here:
        new cadastrodeclientes().setVisible(true);
        dispose();
    }//GEN-LAST:event_RecepcaoActionPerformed

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
        // TODO add your handling code here:
        new Estoque().setVisible(true);
        dispose();
    }//GEN-LAST:event_estoqueActionPerformed

    private void despesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despesasActionPerformed
        // TODO add your handling code here:
        new Despesas().setVisible(true);
        dispose();
    }//GEN-LAST:event_despesasActionPerformed

    private void relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosActionPerformed
        // TODO add your handling code here:
        new relatorios().setVisible(true);
        dispose();
    }//GEN-LAST:event_relatoriosActionPerformed

    private void faturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturamentoActionPerformed
        // TODO add your handling code here:
        new faturamento().setVisible(true);
        dispose();
    }//GEN-LAST:event_faturamentoActionPerformed

    private void encerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarActionPerformed
        // TODO add your handling code here:
        new Programa().setVisible(true);
        dispose();
    }//GEN-LAST:event_encerrarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void salvarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarclienteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
         dispose();
         new Quartos().setVisible(true);
    }//GEN-LAST:event_salvarclienteActionPerformed

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        // TODO add your handling code here:
        new Quartos().setVisible(true);
            dispose();
    }//GEN-LAST:event_reservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrodeclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrodeclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrodeclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrodeclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrodeclientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Recepcao;
    private javax.swing.JButton despesas;
    private javax.swing.JButton encerrar;
    private javax.swing.JButton estoque;
    private javax.swing.JButton faturamento;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField nomehospede1;
    private javax.swing.JButton relatorios;
    private javax.swing.JButton reservas;
    private javax.swing.JButton salvarcliente;
    private javax.swing.JTextField valortotal;
    // End of variables declaration//GEN-END:variables
}
