/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programadeestoque;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.sql.*;
import globaias.*;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.lang.Runtime;

/**
 *
 * @author mathg
 */
public class CHECK_OUT extends javax.swing.JFrame {

    /**
     * Creates new form CHECK_OUT
     */
    public CHECK_OUT() {
        initComponents();
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        
    }
    int id=0;
    String Query;
    String roomType;
    String bed;
    String roomNo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        relatorios = new javax.swing.JButton();
        encerrar = new javax.swing.JButton();
        faturamento = new javax.swing.JButton();
        Recepcao = new javax.swing.JButton();
        despesas = new javax.swing.JButton();
        reservas = new javax.swing.JButton();
        estoque = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/relatorio.png"))); // NOI18N
        relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosActionPerformed(evt);
            }
        });
        jPanel2.add(relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 50, 50));

        encerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/desligar.png"))); // NOI18N
        encerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarActionPerformed(evt);
            }
        });
        jPanel2.add(encerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 60, 60));

        faturamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/faturamento.png"))); // NOI18N
        faturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturamentoActionPerformed(evt);
            }
        });
        jPanel2.add(faturamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 50, 50));

        Recepcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/recep.png"))); // NOI18N
        Recepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecepcaoActionPerformed(evt);
            }
        });
        jPanel2.add(Recepcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 70, 40));

        despesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/despesa.png"))); // NOI18N
        despesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despesasActionPerformed(evt);
            }
        });
        jPanel2.add(despesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 50, 50));

        reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/quartos.png"))); // NOI18N
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });
        jPanel2.add(reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 60, 50));

        estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/estoque.png"))); // NOI18N
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });
        jPanel2.add(estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 60, 50));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 190, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Procurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 200, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 200, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 190, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 270, 180, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 200, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 190, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 190, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 400, 180, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Celular", "Nacionalidade", "Gênero", "Email", "ID Proof", "Address", "Data do Check-IN", "Núm Quarto", "Cama", "Tipo de Quarto", "Preço por dia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 1100, 230));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LIMPAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CHECK-OUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/check out cenario de nigro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1367, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecepcaoActionPerformed
        // TODO add your handling code here:
        new cadastrodeclientes().setVisible(true);
        dispose();
    }//GEN-LAST:event_RecepcaoActionPerformed

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        // TODO add your handling code here:
        new Quartos().setVisible(true);
        dispose();
    }//GEN-LAST:event_reservasActionPerformed

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
        // TODO add your handling code here:
        new Estoque().setVisible(true);
        dispose();
    }//GEN-LAST:event_estoqueActionPerformed

    private void despesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despesasActionPerformed
        // TODO add your handling code here:
        new Despesas().setVisible(true);
        dispose();
    }//GEN-LAST:event_despesasActionPerformed

    private void relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosActionPerformed
        // TODO add your handling code here:
        new relatorios().setVisible(true);
        dispose();
    }//GEN-LAST:event_relatoriosActionPerformed

    private void faturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturamentoActionPerformed
        // TODO add your handling code here:
        new faturamento().setVisible(true);
        dispose();
    }//GEN-LAST:event_faturamentoActionPerformed

    private void encerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarActionPerformed
        // TODO add your handling code here:
        new Programa().setVisible(true);
        dispose();
    }//GEN-LAST:event_encerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String roomNo=jTextField1.getText();
        try
        {
                ResultSet rs=Select.getData("select *from customer where roomNo='"+roomNo+"' and checkout is NULL");
                if(rs.next())
                {
                    jTextField1.setEditable(false);
                    id=rs.getInt(1);
                    jTextField2.setText(rs.getString(2));
                    jTextField3.setText(rs.getString(9));
                    jTextField5.setText(rs.getString(3));
                    jTextField6.setText(rs.getString(13));
                    
                    SimpleDateFormat myFormat=new SimpleDateFormat("dd/mm/yyyy");
                    Calendar cal=Calendar.getInstance();
                    jTextField4.setText(myFormat.format(cal.getTime()));
                    
                    String dateBeforeString=rs.getString(9);
                    java.util.Date date=myFormat.parse(dateBeforeString);
                    String dateAfterStrig=myFormat.format(cal.getTime());
                    java.util.Date dateAfter=myFormat.parse(dateAfterStrig);
                    long difference=dateAfter.getTime() - date.getTime();
                    int noOfDayStay=(int) (difference/1000*60*60*24);
                    if(noOfDayStay==0)
                        noOfDayStay=1;
                    jTextField7.setText(String.valueOf(noOfDayStay));
                    float price=Float.parseFloat(jTextField6.getText());
                    
                    jTextField8.setText(String.valueOf(noOfDayStay*price));
                    jTextField9.setText(rs.getString(6));
                    roomType=rs.getString(12);
                    bed=rs.getString(11);
                    
                    
               }
                else    
                    JOptionPane.showMessageDialog(null, "Este quarto não foi computado ou não existe");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs=Select.getData("select *from customer where checkOut is NULL");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13)});
                rs.close();
        }
        catch(Exception e)
        {
               JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CHECK_OUT().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name=jTextField2.getText();
        String mobileNumber=jTextField5.getText();
        String email=jTextField9.getText();
        
        String checkOut=jTextField4.getText();
        String numberOfDaysStay=jTextField7.getText();
        String totalAmount=jTextField8.getText();
        roomNo=jTextField1.getText();
        Query="update customer set numberOfDaysStay='"+numberOfDaysStay+"',totalAmount='"+totalAmount+"',checkOut='"+checkOut+"',where id='"+id+"'";
        InsertUpdateDelete.setData(Query, "");
        Query="update room set Status='Not Booked' where roomNo='"+roomNo+"'";
        InsertUpdateDelete.setData(Query, "");
        String path="E:\\";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try
        {
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+id+".pdf"));
            doc.open();
            Paragraph paragraph1= new Paragraph("Vanguard Hotel System\n");
            doc.add(paragraph1);
            Paragraph paragraph2= new Paragraph("********************************************************************************************************");
            doc.add(paragraph2);
            Paragraph paragraph3= new Paragraph("\tBill ID: "+id+"\nCustomer Details:\nName:"+name+"\nMobile Number:"+mobileNumber+"\nEmail:"+email+"");
            doc.add(paragraph3);
            doc.add(paragraph2);
            Paragraph paragraph4= new Paragraph("\tRoom Details:\nNumber:"+jTextField1.getText()+"\nType:"+roomType+"\nBed:"+bed+"\nPrice Per Day:"+jTextField6.getText()+"");
            doc.add(paragraph4);
            doc.add(paragraph2);
            PdfPTable tb1=new PdfPTable(4);
            tb1.addCell("Check IN Date:"+jTextField3.getText());
            tb1.addCell("Check Out Date:"+checkOut);
            tb1.addCell("Número de diárias:"+numberOfDaysStay);
            tb1.addCell("Valor total pago:"+totalAmount);
            doc.add(tb1);
            doc.add(paragraph2);
            Paragraph paragraph5= new Paragraph("Muito obrigado, visite-nos de novo na próxima aventura.");
            doc.add(paragraph5);
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }  
        doc.close();
        int a=JOptionPane.showConfirmDialog(null, "Você quer imprimir a nota fiscal?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            try
            {
                if((new File("E:\\"+id+".pdf")).exists())
                        {
                               Process p =Runtime
                                     .getRuntime()
                                     .exec("rund1132 url.dll,FileProtocololHandler E:\\"+id+".pdf");                      
                        }
                        else
                            System.out.println("Este arquivo não existe");
            }
            catch(Exception e)
            {
                    JOptionPane.showMessageDialog(null, e);
            }
            
        }
        setVisible(false);
        new CHECK_OUT().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHECK_OUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHECK_OUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHECK_OUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHECK_OUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHECK_OUT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Recepcao;
    private javax.swing.JButton despesas;
    private javax.swing.JButton encerrar;
    private javax.swing.JButton estoque;
    private javax.swing.JButton faturamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton relatorios;
    private javax.swing.JButton reservas;
    // End of variables declaration//GEN-END:variables
}
