/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programadeestoque;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
/**
 *
 * @author matheus.moliveira36
 */
public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Estoque
     */
    public Estoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reservas = new javax.swing.JButton();
        Recepcao = new javax.swing.JButton();
        estoque = new javax.swing.JButton();
        despesas = new javax.swing.JButton();
        relatorios = new javax.swing.JButton();
        faturamento = new javax.swing.JButton();
        encerrar = new javax.swing.JButton();
        salvarestoque = new javax.swing.JButton();
        agua = new javax.swing.JSpinner();
        toalhademao = new javax.swing.JSpinner();
        toalhadebanho = new javax.swing.JSpinner();
        roupadebanho = new javax.swing.JSpinner();
        roupadecama = new javax.swing.JSpinner();
        papelhig = new javax.swing.JSpinner();
        kitbocal = new javax.swing.JSpinner();
        sabonete = new javax.swing.JSpinner();
        shampoo = new javax.swing.JSpinner();
        condicionador = new javax.swing.JSpinner();
        locaocorporal = new javax.swing.JSpinner();
        secadordecabelo = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/quartos.png"))); // NOI18N
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });
        jPanel1.add(reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        Recepcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/recep.png"))); // NOI18N
        Recepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecepcaoActionPerformed(evt);
            }
        });
        jPanel1.add(Recepcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 60));

        estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/estoque.png"))); // NOI18N
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });
        jPanel1.add(estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        despesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/despesa.png"))); // NOI18N
        despesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despesasActionPerformed(evt);
            }
        });
        jPanel1.add(despesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/relatorio.png"))); // NOI18N
        relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, -1, -1));

        faturamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/faturamento.png"))); // NOI18N
        faturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturamentoActionPerformed(evt);
            }
        });
        jPanel1.add(faturamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 770, -1, -1));

        encerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/desligar.png"))); // NOI18N
        encerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarActionPerformed(evt);
            }
        });
        jPanel1.add(encerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 930, -1, -1));

        salvarestoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/salvar btt.png"))); // NOI18N
        salvarestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarestoqueActionPerformed(evt);
            }
        });
        jPanel1.add(salvarestoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 550, 150, 140));
        jPanel1.add(agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 900, 110, -1));

        toalhademao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                toalhademaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(toalhademao, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 110, -1));
        jPanel1.add(toalhadebanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 110, -1));
        jPanel1.add(roupadebanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 110, -1));
        jPanel1.add(roupadecama, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 110, -1));
        jPanel1.add(papelhig, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 110, -1));
        jPanel1.add(kitbocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 110, -1));
        jPanel1.add(sabonete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 110, -1));
        jPanel1.add(shampoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 660, 110, 20));
        jPanel1.add(condicionador, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 720, 110, -1));
        jPanel1.add(locaocorporal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 780, 110, -1));
        jPanel1.add(secadordecabelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 840, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programadeestoque/newpackage/Estoque cenario.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecepcaoActionPerformed
        // TODO add your handling code here:
        new Quartos().setVisible(true);
        dispose();
    }//GEN-LAST:event_RecepcaoActionPerformed

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
        // TODO add your handling code here:
        new Estoque().setVisible(true);
        dispose();
    }//GEN-LAST:event_estoqueActionPerformed

    private void despesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despesasActionPerformed
        // TODO add your handling code here:
        new Despesas().setVisible(true);
        dispose();
    }//GEN-LAST:event_despesasActionPerformed

    private void relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosActionPerformed
        // TODO add your handling code here:
        new relatorios().setVisible(true);
        dispose();
    }//GEN-LAST:event_relatoriosActionPerformed

    private void faturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturamentoActionPerformed
        // TODO add your handling code here:
        new faturamento().setVisible(true);
        dispose();
    }//GEN-LAST:event_faturamentoActionPerformed

    private void encerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarActionPerformed
        // TODO add your handling code here:
        new Programa().setVisible(true);
        dispose();
    }//GEN-LAST:event_encerrarActionPerformed

    private void salvarestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarestoqueActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Itens salvos com sucesso");
         dispose();
         new Quartos().setVisible(true);
    }//GEN-LAST:event_salvarestoqueActionPerformed

    private void toalhademaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_toalhademaoAncestorAdded
        // TODO add your handling code here:
 
    }//GEN-LAST:event_toalhademaoAncestorAdded

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        // TODO add your handling code here:
        new Quartos().setVisible(true);
            dispose();
    }//GEN-LAST:event_reservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Recepcao;
    private javax.swing.JSpinner agua;
    private javax.swing.JSpinner condicionador;
    private javax.swing.JButton despesas;
    private javax.swing.JButton encerrar;
    private javax.swing.JButton estoque;
    private javax.swing.JButton faturamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner kitbocal;
    private javax.swing.JSpinner locaocorporal;
    private javax.swing.JSpinner papelhig;
    private javax.swing.JButton relatorios;
    private javax.swing.JButton reservas;
    private javax.swing.JSpinner roupadebanho;
    private javax.swing.JSpinner roupadecama;
    private javax.swing.JSpinner sabonete;
    private javax.swing.JButton salvarestoque;
    private javax.swing.JSpinner secadordecabelo;
    private javax.swing.JSpinner shampoo;
    private javax.swing.JSpinner toalhadebanho;
    private javax.swing.JSpinner toalhademao;
    // End of variables declaration//GEN-END:variables
}
